/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Account: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /**
             * @default ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "DELETED" | "INACTIVE";
            /**
             * @default REGISTERED
             * @enum {string}
             */
            type: "REGISTERED" | "CUSTOMER" | "SELLER";
            email?: string | null;
            seller?: components["schemas"]["Seller"] | null;
            customer?: components["schemas"]["Customer"] | null;
            profile?: components["schemas"]["Profile"] | null;
            user?: components["schemas"]["User"];
            userId?: string;
            lists?: components["schemas"]["List"][];
            reviews?: components["schemas"]["Review"][];
            bids?: components["schemas"]["Bid"][];
            listings?: components["schemas"]["Listing"][];
            payouts?: components["schemas"]["Payout"][];
            transactions?: components["schemas"]["Transaction"][];
            shipments?: components["schemas"]["Shipment"][];
            createdOrders?: components["schemas"]["Order"][];
            purchasedOrders?: components["schemas"]["Order"][];
            soldOrders?: components["schemas"]["Order"][];
        };
        Admin: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /**
             * @default ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "DELETED" | "INACTIVE";
            email?: string | null;
            user?: components["schemas"]["User"];
            userId?: string;
            createdBrands?: components["schemas"]["Brand"][];
            lastModifiedBrands?: components["schemas"]["Brand"][];
            createdThemes?: components["schemas"]["Theme"][];
            lastModifiedThemes?: components["schemas"]["Theme"][];
            createdCategories?: components["schemas"]["Category"][];
            lastModifiedCategories?: components["schemas"]["Category"][];
            createdTags?: components["schemas"]["Tag"][];
            lastModifiedTags?: components["schemas"]["Tag"][];
            createdSupportedTagValues?: components["schemas"]["SupportedTagValue"][];
            lastModifiedSupportedTagValues?: components["schemas"]["SupportedTagValue"][];
            createdEntities?: components["schemas"]["Entity"][];
            lastModifiedEntities?: components["schemas"]["Entity"][];
            createdShippingMethods?: components["schemas"]["ShippingMethod"][];
            lastModifiedShippingMethods?: components["schemas"]["ShippingMethod"][];
            createdShippingOptions?: components["schemas"]["ShippingOption"][];
            lastModifiedShippingOptions?: components["schemas"]["ShippingOption"][];
        };
        Bid: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            price?: number;
            quantity?: number;
            /** @enum {string} */
            status?: "ACTIVE" | "DELETED" | "INACTIVE";
            /** @default false */
            multiTransactionsEnabled: boolean | null;
            /**
             * @default MINT
             * @enum {string}
             */
            condition: "MINT" | "NEAR_MINT" | "VERY_GOOD" | "GOOD" | "FAIR" | "POOR" | "DAMAGED";
            account?: components["schemas"]["Account"] | null;
            accountId?: string | null;
            entity?: components["schemas"]["Entity"] | null;
            entityId?: string | null;
            orderBids?: components["schemas"]["OrderBid"][];
            bidShippingMethods?: components["schemas"]["BidShippingMethod"][];
            bidShippingOptions?: components["schemas"]["BidShippingOption"][];
        };
        BidShippingMethod: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            bid?: components["schemas"]["Bid"];
            bidId?: string;
            shippingMethod?: components["schemas"]["ShippingMethod"];
            shippingMethodId?: string;
        };
        BidShippingOption: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            bid?: components["schemas"]["Bid"];
            bidId?: string;
            shippingOption?: components["schemas"]["ShippingOption"];
            shippingOptionId?: string;
        };
        Brand: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            name?: string;
            displayName?: string | null;
            createdBy?: components["schemas"]["Admin"] | null;
            createdById?: string | null;
            lastModifiedBy?: components["schemas"]["Admin"] | null;
            lastModifiedById?: string | null;
            theme?: components["schemas"]["Theme"] | null;
            entities?: components["schemas"]["Entity"][];
        };
        Category: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            name?: string;
            displayName?: string | null;
            description?: string | null;
            createdBy?: components["schemas"]["Admin"] | null;
            createdById?: string | null;
            lastModifiedBy?: components["schemas"]["Admin"] | null;
            lastModifiedById?: string | null;
            entities?: components["schemas"]["Entity"][];
        };
        Customer: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /**
             * @default ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "DELETED" | "INACTIVE";
            paymentAccountId?: string | null;
            /**
             * @default STRIPE
             * @enum {string}
             */
            paymentAccountType: "STRIPE";
            /** @enum {string|null} */
            paymentAccountStatus?: "COMPLETED" | "PENDING" | "CANCELED" | "FAILED" | null;
            /** @default false */
            hasPaymentMethod: boolean | null;
            firstName?: string | null;
            lastName?: string | null;
            phone?: string | null;
            address?: string | null;
            city?: string | null;
            state?: string | null;
            zipCode?: string | null;
            account?: components["schemas"]["Account"];
            accountId?: string;
        };
        Entity: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            name?: string;
            displayName?: string | null;
            description?: string | null;
            /**
             * @default PRODUCT
             * @enum {string}
             */
            type: "PRODUCT" | "SERVICE" | "CONTENT";
            image?: string | null;
            createdBy?: components["schemas"]["Admin"] | null;
            createdById?: string | null;
            lastModifiedBy?: components["schemas"]["Admin"] | null;
            lastModifiedById?: string | null;
            category?: components["schemas"]["Category"] | null;
            categoryId?: string | null;
            brand?: components["schemas"]["Brand"] | null;
            brandId?: string | null;
            product?: components["schemas"]["Product"] | null;
            entityTags?: components["schemas"]["EntityTag"][];
            reviews?: components["schemas"]["Review"][];
            bids?: components["schemas"]["Bid"][];
            listings?: components["schemas"]["Listing"][];
        };
        EntityTag: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            tagValue?: string;
            isPrimary?: boolean | null;
            index?: number | null;
            tag?: components["schemas"]["Tag"];
            tagId?: string;
            entity?: components["schemas"]["Entity"];
            entityId?: string;
        };
        Invoice: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /**
             * @default ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "DELETED" | "INACTIVE";
            orders?: components["schemas"]["Order"][];
        };
        List: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            name?: string;
            displayName?: string | null;
            description?: string | null;
            /** @enum {string|null} */
            type?: "COLLECTION" | "DECK" | "FAVORITE" | null;
            account?: components["schemas"]["Account"] | null;
            accountId?: string | null;
        };
        Listing: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            price?: number;
            quantity?: number;
            /** @enum {string} */
            status?: "ACTIVE" | "DELETED" | "INACTIVE";
            /** @default false */
            multiTransactionsEnabled: boolean;
            /**
             * @default MINT
             * @enum {string}
             */
            condition: "MINT" | "NEAR_MINT" | "VERY_GOOD" | "GOOD" | "FAIR" | "POOR" | "DAMAGED";
            /** @default false */
            isPrimary: boolean | null;
            account?: components["schemas"]["Account"] | null;
            accountId?: string | null;
            entity?: components["schemas"]["Entity"] | null;
            entityId?: string | null;
            orderListings?: components["schemas"]["OrderListing"][];
        };
        Order: {
            id?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            createdAt?: string;
            /** @enum {string} */
            status?: "COMPLETED" | "PENDING" | "CANCELED" | "FAILED";
            subTotal?: number | null;
            taxRate?: number | null;
            tax?: number | null;
            total?: number | null;
            createdBy?: components["schemas"]["Account"] | null;
            createdById?: string | null;
            purchasedBy?: components["schemas"]["Account"] | null;
            purchasedById?: string | null;
            soldBy?: components["schemas"]["Account"] | null;
            soldById?: string | null;
            transactions?: components["schemas"]["Transaction"][];
            shipment?: components["schemas"]["Shipment"] | null;
            invoice?: components["schemas"]["Invoice"];
            invoiceId?: string;
            orderBids?: components["schemas"]["OrderBid"][];
            orderListings?: components["schemas"]["OrderListing"][];
        };
        OrderBid: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            order?: components["schemas"]["Order"];
            orderId?: string;
            bid?: components["schemas"]["Bid"];
            bidId?: string;
        };
        OrderListing: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            order?: components["schemas"]["Order"];
            orderId?: string;
            listing?: components["schemas"]["Listing"];
            listingId?: string;
        };
        Payout: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** @enum {string} */
            status?: "COMPLETED" | "PENDING" | "CANCELED" | "FAILED";
            total?: number | null;
            last4?: string | null;
            account?: components["schemas"]["Account"] | null;
            accountId?: string | null;
            transactions?: components["schemas"]["Transaction"][];
        };
        Product: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /**
             * @default CARD
             * @enum {string}
             */
            type: "CARD";
            /** Format: date-time */
            releaseDate?: string | null;
            weight?: number | null;
            sku?: string | null;
            number?: string | null;
            entity?: components["schemas"]["Entity"];
            entityId?: string;
        };
        Profile: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            username?: string | null;
            image?: string | null;
            qrCode?: string | null;
            account?: components["schemas"]["Account"] | null;
            accountId?: string | null;
        };
        Review: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            rating?: number;
            description?: string;
            account?: components["schemas"]["Account"] | null;
            accountId?: string | null;
            entity?: components["schemas"]["Entity"];
            entityId?: string;
        };
        Seller: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /**
             * @default ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "DELETED" | "INACTIVE";
            paymentAccountId?: string | null;
            /**
             * @default STRIPE
             * @enum {string}
             */
            paymentAccountType: "STRIPE";
            /** @enum {string|null} */
            paymentAccountStatus?: "COMPLETED" | "PENDING" | "CANCELED" | "FAILED" | null;
            /** @default false */
            isPaymentAccountVerified: boolean | null;
            /** @default false */
            hasPaymentMethod: boolean | null;
            /** @enum {string|null} */
            sellerType?: "INDIVIDUAL" | "BUSINESS" | null;
            firstName?: string | null;
            lastName?: string | null;
            phone?: string | null;
            address?: string | null;
            city?: string | null;
            state?: string | null;
            zipCode?: string | null;
            businessName?: string | null;
            website?: string | null;
            account?: components["schemas"]["Account"];
            accountId?: string;
            sellerShippingMethods?: components["schemas"]["SellerShippingMethod"][];
            sellerShippingOptions?: components["schemas"]["SellerShippingOption"][];
            /** @enum {array} */
            shippingCarrierTypes?: "USPS" | "UPS" | "FEDEX" | "DHL";
        };
        SellerShippingMethod: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            seller?: components["schemas"]["Seller"];
            sellerId?: string;
            shippingMethod?: components["schemas"]["ShippingMethod"];
            shippingMethodId?: string;
        };
        SellerShippingOption: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            seller?: components["schemas"]["Seller"];
            sellerId?: string;
            shippingOption?: components["schemas"]["ShippingOption"];
            shippingOptionId?: string;
        };
        Shipment: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            fee?: number | null;
            trackingNumber?: string | null;
            account?: components["schemas"]["Account"] | null;
            accountId?: string | null;
            order?: components["schemas"]["Order"];
            transactionId?: string;
        };
        ShippingMethod: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            name?: string;
            displayName?: string | null;
            description?: string | null;
            /**
             * @default SMALL
             * @enum {string|null}
             */
            size: "EXTRA_SMALL" | "SMALL" | "MEDIUM" | "LARGE" | "EXTRA_LARGE";
            /**
             * @default ENVELOPE
             * @enum {string}
             */
            shippingPackageType: "ENVELOPE" | "BOX";
            /**
             * @default ECONOMY
             * @enum {string}
             */
            shippingServiceType: "FLAT_RATE" | "ECONOMY" | "GROUND" | "FIRST_CLASS" | "PRIORITY" | "EXPRESS" | "OVERNIGHT";
            createdBy?: components["schemas"]["Admin"] | null;
            createdById?: string | null;
            lastModifiedBy?: components["schemas"]["Admin"] | null;
            lastModifiedById?: string | null;
            shippingOptions?: components["schemas"]["ShippingOption"][];
            sellerShippingMethods?: components["schemas"]["SellerShippingMethod"][];
            bidShippingMethods?: components["schemas"]["BidShippingMethod"][];
        };
        ShippingOption: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            name?: string;
            displayName?: string | null;
            description?: string | null;
            maxQuantity?: number | null;
            maxWeight?: number | null;
            rate?: number;
            /** @default false */
            isStandalone: boolean | null;
            createdBy?: components["schemas"]["Admin"] | null;
            createdById?: string | null;
            lastModifiedBy?: components["schemas"]["Admin"] | null;
            lastModifiedById?: string | null;
            shippingMethod?: components["schemas"]["ShippingMethod"] | null;
            shippingMethodId?: string | null;
            sellerShippingOptions?: components["schemas"]["SellerShippingOption"][];
            bidShippingOptions?: components["schemas"]["BidShippingOption"][];
        };
        SupportedTagValue: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            name?: string;
            displayName?: string | null;
            createdBy?: components["schemas"]["Admin"] | null;
            createdById?: string | null;
            lastModifiedBy?: components["schemas"]["Admin"] | null;
            lastModifiedById?: string | null;
            tag?: components["schemas"]["Tag"];
            tagId?: string;
        };
        Tag: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            name?: string;
            displayName?: string | null;
            createdBy?: components["schemas"]["Admin"] | null;
            createdById?: string | null;
            lastModifiedBy?: components["schemas"]["Admin"] | null;
            lastModifiedById?: string | null;
            entityTags?: components["schemas"]["EntityTag"][];
            supportedTagValues?: components["schemas"]["SupportedTagValue"][];
        };
        Theme: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            logo?: string | null;
            primaryColor?: string | null;
            secondaryColor?: string | null;
            createdBy?: components["schemas"]["Admin"] | null;
            createdById?: string | null;
            lastModifiedBy?: components["schemas"]["Admin"] | null;
            lastModifiedById?: string | null;
            brand?: components["schemas"]["Brand"];
            brandId?: string;
        };
        Transaction: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            amount?: number;
            refundedAmount?: number | null;
            /**
             * @default ORDER_PAYMENT
             * @enum {string}
             */
            transactionType: "ORDER_PAYMENT" | "ORDER_REFUND" | "PAYOUT";
            description?: string | null;
            /**
             * @default USD
             * @enum {string}
             */
            currency: "USD" | "EUR" | "CAD";
            paymentId?: string | null;
            /**
             * @default STRIPE
             * @enum {string}
             */
            paymentAccountType: "STRIPE";
            /**
             * @default CARD
             * @enum {string}
             */
            paymentMethodType: "CARD" | "BANK_ACCOUNT" | "APPLE_PAY";
            account?: components["schemas"]["Account"] | null;
            accountId?: string | null;
            order?: components["schemas"]["Order"] | null;
            orderId?: string | null;
            payout?: components["schemas"]["Payout"] | null;
            payoutId?: string | null;
        };
        User: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /**
             * @default ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "DELETED" | "INACTIVE";
            authId?: string;
            /** @default false */
            isAdmin: boolean | null;
            account?: components["schemas"]["Account"] | null;
            admin?: components["schemas"]["Admin"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
