/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Account: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /**
             * @default ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "DELETED" | "INACTIVE";
            /**
             * @default REGISTERED
             * @enum {string}
             */
            type: "REGISTERED" | "CUSTOMER" | "SELLER";
            email?: string | null;
            carts?: components["schemas"]["Cart"][];
            seller?: components["schemas"]["Seller"] | null;
            customer?: components["schemas"]["Customer"] | null;
            profile?: components["schemas"]["Profile"] | null;
            user?: components["schemas"]["User"];
            userId?: string;
            lists?: components["schemas"]["List"][];
            reviews?: components["schemas"]["Review"][];
            bids?: components["schemas"]["Bid"][];
            listings?: components["schemas"]["Listing"][];
            payouts?: components["schemas"]["Payout"][];
            transactions?: components["schemas"]["Transaction"][];
        };
        Admin: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /**
             * @default ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "DELETED" | "INACTIVE";
            email?: string | null;
            user?: components["schemas"]["User"];
            userId?: string;
            createdBrands?: components["schemas"]["Brand"][];
            lastModifiedBrands?: components["schemas"]["Brand"][];
            createdThemes?: components["schemas"]["Theme"][];
            lastModifiedThemes?: components["schemas"]["Theme"][];
            createdCategories?: components["schemas"]["Category"][];
            lastModifiedCategories?: components["schemas"]["Category"][];
            createdTags?: components["schemas"]["Tag"][];
            lastModifiedTags?: components["schemas"]["Tag"][];
            createdSupportedTagValues?: components["schemas"]["SupportedTagValue"][];
            lastModifiedSupportedTagValues?: components["schemas"]["SupportedTagValue"][];
            createdEntities?: components["schemas"]["Entity"][];
            lastModifiedEntities?: components["schemas"]["Entity"][];
            createdShippingMethods?: components["schemas"]["ShippingMethod"][];
            lastModifiedShippingMethods?: components["schemas"]["ShippingMethod"][];
            createdShippingOptions?: components["schemas"]["ShippingOption"][];
            lastModifiedShippingOptions?: components["schemas"]["ShippingOption"][];
        };
        Bid: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            price?: number;
            quantity?: number;
            /** @enum {string} */
            status?: "ACTIVE" | "DELETED" | "INACTIVE";
            /** @default false */
            multiTransactionsEnabled: boolean | null;
            /**
             * @default MINT
             * @enum {string}
             */
            condition: "MINT" | "NEAR_MINT" | "VERY_GOOD" | "GOOD" | "FAIR" | "POOR" | "DAMAGED";
            account?: components["schemas"]["Account"] | null;
            accountId?: string | null;
            entity?: components["schemas"]["Entity"] | null;
            entityId?: string | null;
            offers?: components["schemas"]["Offer"][];
        };
        Brand: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            name?: string;
            displayName?: string | null;
            logo?: string | null;
            createdBy?: components["schemas"]["Admin"] | null;
            createdById?: string | null;
            lastModifiedBy?: components["schemas"]["Admin"] | null;
            lastModifiedById?: string | null;
            theme?: components["schemas"]["Theme"] | null;
            entities?: components["schemas"]["Entity"][];
        };
        Cart: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** @default false */
            isPrimary: boolean | null;
            account?: components["schemas"]["Account"] | null;
            accountId?: string | null;
            orders?: components["schemas"]["Order"][];
        };
        Category: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            name?: string;
            displayName?: string | null;
            description?: string | null;
            createdBy?: components["schemas"]["Admin"] | null;
            createdById?: string | null;
            lastModifiedBy?: components["schemas"]["Admin"] | null;
            lastModifiedById?: string | null;
            entities?: components["schemas"]["Entity"][];
        };
        Customer: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /**
             * @default ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "DELETED" | "INACTIVE";
            paymentAccountId?: string | null;
            /**
             * @default STRIPE
             * @enum {string}
             */
            paymentAccountType: "STRIPE";
            /** @enum {string|null} */
            paymentAccountStatus?: "CREATED" | "DELETED" | "PENDING" | "COMPLETED" | "CANCELED" | "FAILED" | null;
            /** @default false */
            hasPaymentMethod: boolean | null;
            firstName?: string | null;
            lastName?: string | null;
            phone?: string | null;
            address?: string | null;
            city?: string | null;
            state?: string | null;
            zipCode?: string | null;
            account?: components["schemas"]["Account"];
            accountId?: string;
            orders?: components["schemas"]["Order"][];
        };
        Entity: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            name?: string;
            displayName?: string | null;
            description?: string | null;
            /**
             * @default PRODUCT
             * @enum {string}
             */
            type: "PRODUCT" | "SERVICE" | "CONTENT" | "EVENT";
            image?: string | null;
            secondaryImage?: string | null;
            createdBy?: components["schemas"]["Admin"] | null;
            createdById?: string | null;
            lastModifiedBy?: components["schemas"]["Admin"] | null;
            lastModifiedById?: string | null;
            category?: components["schemas"]["Category"] | null;
            categoryId?: string | null;
            brand?: components["schemas"]["Brand"] | null;
            brandId?: string | null;
            product?: components["schemas"]["Product"] | null;
            entityTags?: components["schemas"]["EntityTag"][];
            entityList?: components["schemas"]["EntityList"][];
            reviews?: components["schemas"]["Review"][];
            bids?: components["schemas"]["Bid"][];
            listings?: components["schemas"]["Listing"][];
        };
        EntityList: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            list?: components["schemas"]["List"];
            listId?: string;
            entity?: components["schemas"]["Entity"];
            entityId?: string;
        };
        EntityTag: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            tagValue?: string;
            isPrimary?: boolean | null;
            index?: number | null;
            tag?: components["schemas"]["Tag"];
            tagId?: string;
            entity?: components["schemas"]["Entity"];
            entityId?: string;
        };
        Invoice: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /**
             * @default ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "DELETED" | "INACTIVE";
            orders?: components["schemas"]["Order"][];
        };
        List: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            name?: string;
            displayName?: string | null;
            description?: string | null;
            /**
             * @default DEFAULT
             * @enum {string|null}
             */
            type: "DEFAULT" | "COLLECTION" | "DECK";
            account?: components["schemas"]["Account"] | null;
            accountId?: string | null;
            entityList?: components["schemas"]["EntityList"][];
        };
        Listing: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            price?: number;
            quantity?: number;
            /** @enum {string} */
            status?: "ACTIVE" | "DELETED" | "INACTIVE";
            /** @default false */
            multiTransactionsEnabled: boolean;
            /**
             * @default MINT
             * @enum {string}
             */
            condition: "MINT" | "NEAR_MINT" | "VERY_GOOD" | "GOOD" | "FAIR" | "POOR" | "DAMAGED";
            /** @default false */
            isPrimary: boolean | null;
            /** @default false */
            isOffer: boolean | null;
            image?: string | null;
            imageCaption?: string | null;
            account?: components["schemas"]["Account"] | null;
            accountId?: string | null;
            entity?: components["schemas"]["Entity"] | null;
            entityId?: string | null;
            orderListings?: components["schemas"]["OrderListing"][];
            offer?: components["schemas"]["Offer"] | null;
        };
        Offer: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /**
             * @default PENDING
             * @enum {string}
             */
            status: "PENDING" | "ACCEPTED" | "DECLINED" | "CANCELED";
            bid?: components["schemas"]["Bid"] | null;
            bidId?: string | null;
            listing?: components["schemas"]["Listing"] | null;
            listingId?: string | null;
            order?: components["schemas"]["Order"] | null;
        };
        Order: {
            id?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            createdAt?: string;
            /** @enum {string} */
            status?: "CREATED" | "DELETED" | "PENDING" | "COMPLETED" | "CANCELED" | "FAILED";
            subTotal?: number | null;
            tax?: number | null;
            shipping?: number | null;
            total?: number | null;
            cart?: components["schemas"]["Cart"] | null;
            cartId?: string | null;
            customer?: components["schemas"]["Customer"] | null;
            customerId?: string | null;
            seller?: components["schemas"]["Seller"] | null;
            sellerId?: string | null;
            transactions?: components["schemas"]["Transaction"][];
            shipments?: components["schemas"]["Shipment"][];
            invoice?: components["schemas"]["Invoice"] | null;
            invoiceId?: string | null;
            orderListings?: components["schemas"]["OrderListing"][];
            shippingMethod?: components["schemas"]["ShippingMethod"] | null;
            shippingMethodId?: string | null;
            orderShippingOptions?: components["schemas"]["OrderShippingOption"][];
            offer?: components["schemas"]["Offer"] | null;
            offerId?: string | null;
        };
        OrderListing: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            quantity?: number | null;
            order?: components["schemas"]["Order"];
            orderId?: string;
            listing?: components["schemas"]["Listing"];
            listingId?: string;
        };
        OrderShippingOption: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            order?: components["schemas"]["Order"];
            orderId?: string;
            shippingOption?: components["schemas"]["ShippingOption"];
            shippingOptionId?: string;
        };
        Parcel: {
            id?: string;
            /** @enum {string} */
            carrier?: "USPS" | "UPS" | "FEDEX" | "DHL";
            /** @enum {string} */
            type?: "USPS_FlatRateEnvelope" | "USPS_SoftPack" | "UPS_Box_10kg" | "UPS_Box_25kg" | "UPS_Pad_Pak" | "FedEx_Envelope" | "FedEx_Padded_Pak" | "FedEx_Box_10kg" | "FedEx_Box_25kg";
            shippingMethod?: components["schemas"]["ShippingMethod"] | null;
            shippingMethodId?: string | null;
        };
        Payout: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** @enum {string} */
            status?: "CREATED" | "DELETED" | "PENDING" | "COMPLETED" | "CANCELED" | "FAILED";
            total?: number | null;
            last4?: string | null;
            account?: components["schemas"]["Account"] | null;
            accountId?: string | null;
            transactions?: components["schemas"]["Transaction"][];
        };
        Product: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /**
             * @default CARD
             * @enum {string}
             */
            type: "CARD";
            /** Format: date-time */
            releaseDate?: string | null;
            weight?: number | null;
            width?: number | null;
            length?: number | null;
            height?: number | null;
            sku?: string | null;
            number?: string | null;
            price?: number | null;
            entity?: components["schemas"]["Entity"];
            entityId?: string;
        };
        Profile: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            username?: string | null;
            avatar?: string | null;
            banner?: string | null;
            description?: string | null;
            qrCode?: string | null;
            account?: components["schemas"]["Account"] | null;
            accountId?: string | null;
        };
        Review: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            rating?: number;
            description?: string;
            account?: components["schemas"]["Account"] | null;
            accountId?: string | null;
            entity?: components["schemas"]["Entity"];
            entityId?: string;
        };
        Seller: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /**
             * @default ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "DELETED" | "INACTIVE";
            paymentAccountId?: string | null;
            /**
             * @default STRIPE
             * @enum {string}
             */
            paymentAccountType: "STRIPE";
            /** @enum {string|null} */
            paymentAccountStatus?: "CREATED" | "DELETED" | "PENDING" | "COMPLETED" | "CANCELED" | "FAILED" | null;
            /** @default false */
            isPaymentAccountVerified: boolean | null;
            /** @default false */
            hasPaymentMethod: boolean | null;
            /** @enum {string|null} */
            sellerType?: "INDIVIDUAL" | "BUSINESS" | null;
            taxRate?: number | null;
            firstName?: string | null;
            lastName?: string | null;
            phone?: string | null;
            address?: string | null;
            city?: string | null;
            state?: string | null;
            zipCode?: string | null;
            businessName?: string | null;
            website?: string | null;
            /** @enum {array} */
            shippingCarrierTypes?: "USPS" | "UPS" | "FEDEX" | "DHL";
            account?: components["schemas"]["Account"];
            accountId?: string;
            sellerShippingMethods?: components["schemas"]["SellerShippingMethod"][];
            sellerShippingOptions?: components["schemas"]["SellerShippingOption"][];
            orders?: components["schemas"]["Order"][];
        };
        SellerShippingMethod: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            seller?: components["schemas"]["Seller"];
            sellerId?: string;
            shippingMethod?: components["schemas"]["ShippingMethod"];
            shippingMethodId?: string;
        };
        SellerShippingOption: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            seller?: components["schemas"]["Seller"];
            sellerId?: string;
            shippingOption?: components["schemas"]["ShippingOption"];
            shippingOptionId?: string;
        };
        Shipment: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            name?: string | null;
            displayName?: string | null;
            description?: string | null;
            /**
             * @default OUTBOUND
             * @enum {string}
             */
            type: "OUTBOUND" | "RETURN";
            /**
             * @default SHIPPO
             * @enum {string}
             */
            shipmentAccountType: "SHIPPO";
            /** @enum {string} */
            status?: "CREATED" | "DELETED" | "PENDING" | "COMPLETED" | "CANCELED" | "FAILED";
            rate?: number;
            trackingNumber?: string | null;
            /**
             * @default UNKNOWN
             * @enum {string|null}
             */
            trackingStatus: "UNKNOWN" | "PRE_TRANSIT" | "TRANSIT" | "OUT_FOR_DELIVERY" | "DELIVERED" | "RETURNED" | "FAILURE";
            labelUrl?: string | null;
            externalShipmentId?: string | null;
            externalShipmentRateId?: string | null;
            externalShipmentServiceId?: string | null;
            externalShipmentCarrierId?: string | null;
            order?: components["schemas"]["Order"] | null;
            orderId?: string | null;
        };
        ShippingMethod: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            name?: string;
            displayName?: string | null;
            description?: string | null;
            createdBy?: components["schemas"]["Admin"] | null;
            createdById?: string | null;
            lastModifiedBy?: components["schemas"]["Admin"] | null;
            lastModifiedById?: string | null;
            orders?: components["schemas"]["Order"][];
            parcels?: components["schemas"]["Parcel"][];
            shippingOptions?: components["schemas"]["ShippingOption"][];
            sellerShippingMethods?: components["schemas"]["SellerShippingMethod"][];
        };
        ShippingOption: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            name?: string;
            displayName?: string | null;
            description?: string | null;
            weight?: number | null;
            rate?: number;
            /** @default false */
            isStandalone: boolean | null;
            maxQuantity?: number | null;
            createdBy?: components["schemas"]["Admin"] | null;
            createdById?: string | null;
            lastModifiedBy?: components["schemas"]["Admin"] | null;
            lastModifiedById?: string | null;
            shippingMethod?: components["schemas"]["ShippingMethod"] | null;
            shippingMethodId?: string | null;
            sellerShippingOptions?: components["schemas"]["SellerShippingOption"][];
            orderShippingOptions?: components["schemas"]["OrderShippingOption"][];
        };
        SupportedTagValue: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            name?: string;
            displayName?: string | null;
            createdBy?: components["schemas"]["Admin"] | null;
            createdById?: string | null;
            lastModifiedBy?: components["schemas"]["Admin"] | null;
            lastModifiedById?: string | null;
            tag?: components["schemas"]["Tag"];
            tagId?: string;
        };
        Tag: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            name?: string;
            displayName?: string | null;
            createdBy?: components["schemas"]["Admin"] | null;
            createdById?: string | null;
            lastModifiedBy?: components["schemas"]["Admin"] | null;
            lastModifiedById?: string | null;
            entityTags?: components["schemas"]["EntityTag"][];
            supportedTagValues?: components["schemas"]["SupportedTagValue"][];
        };
        Theme: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            logo?: string | null;
            primaryColor?: string | null;
            secondaryColor?: string | null;
            createdBy?: components["schemas"]["Admin"] | null;
            createdById?: string | null;
            lastModifiedBy?: components["schemas"]["Admin"] | null;
            lastModifiedById?: string | null;
            brand?: components["schemas"]["Brand"];
            brandId?: string;
        };
        Transaction: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            amount?: number;
            refundedAmount?: number | null;
            /**
             * @default PAYMENT
             * @enum {string}
             */
            transactionType: "PAYMENT" | "REFUND" | "PAYOUT";
            description?: string | null;
            /**
             * @default USD
             * @enum {string}
             */
            currency: "USD" | "EUR" | "CAD";
            paymentId?: string | null;
            /**
             * @default STRIPE
             * @enum {string}
             */
            paymentAccountType: "STRIPE";
            /**
             * @default CARD
             * @enum {string}
             */
            paymentMethodType: "CARD" | "BANK_ACCOUNT" | "APPLE_PAY";
            account?: components["schemas"]["Account"] | null;
            accountId?: string | null;
            order?: components["schemas"]["Order"] | null;
            orderId?: string | null;
            payout?: components["schemas"]["Payout"] | null;
            payoutId?: string | null;
        };
        User: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /**
             * @default ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "DELETED" | "INACTIVE";
            authId?: string;
            /** @default false */
            isAdmin: boolean | null;
            account?: components["schemas"]["Account"] | null;
            admin?: components["schemas"]["Admin"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
