/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Account: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /**
             * @default ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "DELETED" | "INACTIVE";
            /**
             * @default CUSTOMER
             * @enum {string}
             */
            type: "ADMIN" | "MARKET_MANAGER" | "BRAND_MANAGER" | "CUSTOMER" | "SELLER";
            /** @default false */
            isPremium: boolean | null;
            phone?: string | null;
            email?: string | null;
            firstName?: string | null;
            lastName?: string | null;
            address?: string | null;
            city?: string | null;
            state?: string | null;
            zipCode?: string | null;
            paymentCustomerId?: string | null;
            /**
             * @default STRIPE
             * @enum {string}
             */
            paymentProcessorType: "STRIPE";
            profile?: components["schemas"]["Profile"] | null;
            wallet?: components["schemas"]["Wallet"] | null;
            user?: components["schemas"]["User"];
            userId?: string;
            createdOrders?: components["schemas"]["Order"][];
            purchasedOrders?: components["schemas"]["Order"][];
            soldOrders?: components["schemas"]["Order"][];
        };
        Bid: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            price?: number;
            quantity?: number;
            /** @enum {string} */
            status?: "ACTIVE" | "DELETED" | "INACTIVE";
            /** @default false */
            multiTransactionsEnabled: boolean | null;
            profile?: components["schemas"]["Profile"] | null;
            profileId?: string | null;
            entity?: components["schemas"]["Entity"] | null;
            entityId?: string | null;
            orderBids?: components["schemas"]["OrderBid"][];
            bidShippingCategories?: components["schemas"]["BidShippingCategory"][];
            bidCustomShippingOptions?: components["schemas"]["BidCustomShippingOption"][];
        };
        BidCustomShippingOption: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            bid?: components["schemas"]["Bid"];
            bidId?: string;
            shippingOption?: components["schemas"]["ShippingOption"];
            shippingOptionId?: string;
        };
        BidShippingCategory: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            bid?: components["schemas"]["Bid"];
            bidId?: string;
            shippingCategory?: components["schemas"]["ShippingCategory"];
            shippingCategoryId?: string;
        };
        Brand: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            name?: string;
            displayName?: string | null;
            marketplace?: components["schemas"]["Marketplace"];
            marketplaceName?: string;
            theme?: components["schemas"]["Theme"] | null;
            brandCategories?: components["schemas"]["BrandCategory"][];
        };
        BrandCategory: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            brand?: components["schemas"]["Brand"];
            brandName?: string;
            category?: components["schemas"]["Category"];
            categoryName?: string;
            lists?: components["schemas"]["List"][];
            entities?: components["schemas"]["Entity"][];
        };
        Category: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            name?: string;
            displayName?: string | null;
            marketplace?: components["schemas"]["Marketplace"];
            marketplaceName?: string;
            brandCategories?: components["schemas"]["BrandCategory"][];
        };
        Entity: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            name?: string;
            displayName?: string | null;
            description?: string | null;
            /**
             * @default PRODUCT
             * @enum {string}
             */
            type: "PRODUCT" | "SERVICE" | "CONTENT";
            image?: string | null;
            product?: components["schemas"]["Product"] | null;
            brandCategory?: components["schemas"]["BrandCategory"];
            brandCategoryId?: string;
            list?: components["schemas"]["List"] | null;
            listId?: string | null;
            entityTags?: components["schemas"]["EntityTag"][];
            reviews?: components["schemas"]["Review"][];
            bids?: components["schemas"]["Bid"][];
            listings?: components["schemas"]["Listing"][];
        };
        EntityTag: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            tagValue?: string;
            isPrimary?: boolean | null;
            index?: number | null;
            tag?: components["schemas"]["Tag"];
            tagId?: string;
            entity?: components["schemas"]["Entity"];
            entityId?: string;
        };
        Invoice: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /**
             * @default ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "DELETED" | "INACTIVE";
            orders?: components["schemas"]["Order"][];
            payouts?: components["schemas"]["Payout"][];
        };
        List: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            name?: string;
            displayName?: string | null;
            description?: string | null;
            /** @enum {string|null} */
            type?: "COLLECTION" | "SET" | "DECK" | "FAVORITE" | null;
            brandCategory?: components["schemas"]["BrandCategory"];
            brandCategoryId?: string;
            entities?: components["schemas"]["Entity"][];
            profile?: components["schemas"]["Profile"];
            profileId?: string;
        };
        Listing: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            price?: number;
            quantity?: number;
            /** @enum {string} */
            status?: "ACTIVE" | "DELETED" | "INACTIVE";
            /** @default false */
            multiTransactionsEnabled: boolean;
            /**
             * @default MINT
             * @enum {string}
             */
            condition: "MINT" | "NEAR_MINT" | "VERY_GOOD" | "GOOD" | "FAIR" | "POOR" | "DAMAGED";
            /** @default false */
            isPrimary: boolean | null;
            profile?: components["schemas"]["Profile"] | null;
            profileId?: string | null;
            entity?: components["schemas"]["Entity"] | null;
            entityId?: string | null;
            orderListings?: components["schemas"]["OrderListing"][];
            listingShippingCategories?: components["schemas"]["ListingShippingCategory"][];
            listingCustomShippingOptions?: components["schemas"]["ListingCustomShippingOption"][];
        };
        ListingCustomShippingOption: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            listing?: components["schemas"]["Listing"];
            listingId?: string;
            shippingOption?: components["schemas"]["ShippingOption"];
            shippingOptionId?: string;
        };
        ListingShippingCategory: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            listing?: components["schemas"]["Listing"];
            listingId?: string;
            shippingCategory?: components["schemas"]["ShippingCategory"];
            shippingCategoryId?: string;
        };
        Marketplace: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            name?: string;
            displayName?: string | null;
            /** @default false */
            hasMultiSellerEnabled: boolean | null;
            theme?: components["schemas"]["Theme"] | null;
            brands?: components["schemas"]["Brand"][];
            categories?: components["schemas"]["Category"][];
            shippingCategories?: components["schemas"]["ShippingCategory"][];
            tags?: components["schemas"]["Tag"][];
        };
        Order: {
            id?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            createdAt?: string;
            /** @enum {string} */
            status?: "COMPLETED" | "PENDING" | "CANCELED";
            subTotal?: number | null;
            taxRate?: number | null;
            tax?: number | null;
            total?: number | null;
            createdBy?: components["schemas"]["Account"] | null;
            createdById?: string | null;
            purchasedBy?: components["schemas"]["Account"] | null;
            purchasedById?: string | null;
            soldBy?: components["schemas"]["Account"] | null;
            soldById?: string | null;
            transactions?: components["schemas"]["Transaction"][];
            shipment?: components["schemas"]["Shipment"] | null;
            invoice?: components["schemas"]["Invoice"];
            invoiceId?: string;
            orderBids?: components["schemas"]["OrderBid"][];
            orderListings?: components["schemas"]["OrderListing"][];
        };
        OrderBid: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            order?: components["schemas"]["Order"];
            orderId?: string;
            bid?: components["schemas"]["Bid"];
            bidId?: string;
        };
        OrderListing: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            order?: components["schemas"]["Order"];
            orderId?: string;
            listing?: components["schemas"]["Listing"];
            listingId?: string;
        };
        Payout: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** @enum {string} */
            status?: "COMPLETED" | "PENDING" | "CANCELED";
            subTotal?: number | null;
            taxRate?: number | null;
            tax?: number | null;
            total?: number | null;
            transactions?: components["schemas"]["Transaction"][];
            wallet?: components["schemas"]["Wallet"];
            walletId?: string;
            invoice?: components["schemas"]["Invoice"];
            invoiceId?: string;
        };
        Product: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /**
             * @default CARD
             * @enum {string}
             */
            type: "CARD";
            /** Format: date-time */
            releaseDate?: string | null;
            weight?: number | null;
            sku?: string | null;
            number?: string | null;
            entity?: components["schemas"]["Entity"];
            entityId?: string;
        };
        Profile: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            username?: string | null;
            /** @default false */
            isPrivate: boolean | null;
            fullName?: string | null;
            image?: string | null;
            qrCode?: string | null;
            account?: components["schemas"]["Account"];
            accountId?: string;
            lists?: components["schemas"]["List"][];
            reviews?: components["schemas"]["Review"][];
            bids?: components["schemas"]["Bid"][];
            listings?: components["schemas"]["Listing"][];
        };
        Review: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            rating?: number;
            description?: string;
            profile?: components["schemas"]["Profile"];
            profileId?: string;
            entity?: components["schemas"]["Entity"];
            entityId?: string;
        };
        Shipment: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            fee?: number | null;
            /** @enum {string} */
            deliveryType?: "USPS" | "UPS" | "FEDEX" | "IN_PERSON";
            /** @enum {string} */
            deliveryMethodType?: "FIRST_CLASS_MAIL" | "NEXT_DAY_AIR" | "OVERNIGHT" | "PRIORITY" | "FLAT_RATE" | "EXPRESS" | "ECONOMY" | "INTERNATIONAL" | "IN_PERSON";
            trackingNumber?: string | null;
            order?: components["schemas"]["Order"];
            transactionId?: string;
        };
        ShippingCategory: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            name?: string;
            displayName?: string | null;
            description?: string | null;
            level?: number | null;
            /**
             * @default USPS
             * @enum {string|null}
             */
            deliveryType: "USPS" | "UPS" | "FEDEX" | "IN_PERSON";
            /**
             * @default ECONOMY
             * @enum {string|null}
             */
            deliveryMethodType: "FIRST_CLASS_MAIL" | "NEXT_DAY_AIR" | "OVERNIGHT" | "PRIORITY" | "FLAT_RATE" | "EXPRESS" | "ECONOMY" | "INTERNATIONAL" | "IN_PERSON";
            marketplace?: components["schemas"]["Marketplace"];
            marketplaceName?: string;
            shippingOptions?: components["schemas"]["ShippingOption"][];
            listingShippingCategories?: components["schemas"]["ListingShippingCategory"][];
            bidShippingCategories?: components["schemas"]["BidShippingCategory"][];
        };
        ShippingOption: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            name?: string;
            displayName?: string | null;
            description?: string | null;
            maxQuantity?: number | null;
            maxWeight?: number | null;
            rate?: number;
            isRequired?: boolean | null;
            shippingCategory?: components["schemas"]["ShippingCategory"] | null;
            shippingCategoryId?: string | null;
            listingCustomShippingOptions?: components["schemas"]["ListingCustomShippingOption"][];
            bidCustomShippingOptions?: components["schemas"]["BidCustomShippingOption"][];
        };
        SupportedTagValues: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            name?: string;
            displayName?: string | null;
            tag?: components["schemas"]["Tag"];
            tagId?: string;
        };
        Tag: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            name?: string;
            displayName?: string | null;
            marketplace?: components["schemas"]["Marketplace"];
            marketplaceName?: string;
            entityTags?: components["schemas"]["EntityTag"][];
            supportedTagValues?: components["schemas"]["SupportedTagValues"][];
        };
        Theme: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            logo?: string | null;
            primaryColor?: string | null;
            secondaryColor?: string | null;
            marketplace?: components["schemas"]["Marketplace"];
            marketplaceId?: string;
            brand?: components["schemas"]["Brand"];
            brandId?: string;
        };
        Transaction: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            amount?: number;
            refundedAmount?: number | null;
            /**
             * @default ORDER
             * @enum {string}
             */
            transactionType: "ORDER" | "PAYOUT";
            /** @enum {string} */
            status?: "COMPLETED" | "FAILED" | "PENDING" | "CANCELED" | "REFUNDED" | "REQUIRES_ACTION";
            description?: string | null;
            /**
             * @default USD
             * @enum {string}
             */
            currency: "USD" | "EUR" | "CAD";
            paymentId?: string | null;
            /**
             * @default STRIPE
             * @enum {string}
             */
            paymentProcessorType: "STRIPE";
            /**
             * @default CARD
             * @enum {string}
             */
            paymentMethodType: "CARD" | "BANK_ACCOUNT" | "APPLE_PAY";
            order?: components["schemas"]["Order"] | null;
            orderId?: string | null;
            payout?: components["schemas"]["Payout"] | null;
            payoutId?: string | null;
        };
        User: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /**
             * @default ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "DELETED" | "INACTIVE";
            authId?: string;
            /** @default false */
            isAdmin: boolean | null;
            account?: components["schemas"]["Account"] | null;
        };
        Wallet: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            balance?: number;
            payouts?: components["schemas"]["Payout"][];
            account?: components["schemas"]["Account"];
            accountId?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
