/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */
export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Account: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /**
             * @default ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "INACTIVE" | "DELETED";
            /**
             * @default STANDARD
             * @enum {string}
             */
            type: "STANDARD" | "SELLER";
            /** @default false */
            isPremium: boolean | null;
            phone?: string | null;
            email?: string | null;
            firstName?: string | null;
            lastName?: string | null;
            address?: string | null;
            city?: string | null;
            state?: string | null;
            zipCode?: string | null;
            profile?: components["schemas"]["Profile"] | null;
            wallet?: components["schemas"]["Wallet"] | null;
            user?: components["schemas"]["User"];
            userId?: string;
        };
        Bid: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            price?: number | null;
            quantity?: number | null;
            /** @enum {string|null} */
            status?: "ACTIVE" | "INACTIVE" | "DELETED" | null;
            /** @default false */
            multiTransactionsEnabled: boolean | null;
            profile?: components["schemas"]["Profile"] | null;
            profileId?: string | null;
            product?: components["schemas"]["Product"] | null;
            productId?: string | null;
            transactions?: components["schemas"]["Transaction"][];
            bidShippingCategories?: components["schemas"]["BidShippingCategory"][];
        };
        BidShippingCategory: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            bid?: components["schemas"]["Bid"];
            bidId?: string;
            shippingCategory?: components["schemas"]["ShippingCategory"];
            shippingCategoryId?: string;
        };
        Brand: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            name?: string;
            displayName?: string | null;
            marketplace?: components["schemas"]["Marketplace"] | null;
            marketplaceName?: string | null;
            theme?: components["schemas"]["Theme"] | null;
            brandCategories?: components["schemas"]["BrandCategory"][];
        };
        BrandCategory: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            brand?: components["schemas"]["Brand"];
            brandName?: string;
            category?: components["schemas"]["Category"] | null;
            categoryName?: string;
            lists?: components["schemas"]["List"][];
            products?: components["schemas"]["Product"][];
            cards?: components["schemas"]["Card"][];
        };
        Card: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            number?: string | null;
            brandCategory?: components["schemas"]["BrandCategory"] | null;
            brandCategoryId?: string | null;
            product?: components["schemas"]["Product"] | null;
            productId?: string | null;
        };
        Category: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            name?: string;
            displayName?: string | null;
            marketplace?: components["schemas"]["Marketplace"] | null;
            marketplaceName?: string | null;
            brandCategories?: components["schemas"]["BrandCategory"][];
        };
        List: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            displayName?: string | null;
            name?: string | null;
            description?: string | null;
            /** @enum {string|null} */
            type?: "COLLECTION" | "SET" | "DECK" | "FAVORITE" | null;
            brandCategory?: components["schemas"]["BrandCategory"] | null;
            brandCategoryId?: string | null;
            products?: components["schemas"]["Product"][];
            profile?: components["schemas"]["Profile"] | null;
            profileId?: string | null;
        };
        Listing: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            price?: number | null;
            quantity?: number | null;
            /** @enum {string|null} */
            status?: "ACTIVE" | "INACTIVE" | "DELETED" | null;
            /** @default false */
            multiTransactionsEnabled: boolean;
            profile?: components["schemas"]["Profile"] | null;
            profileId?: string | null;
            product?: components["schemas"]["Product"] | null;
            productId?: string | null;
            transactions?: components["schemas"]["Transaction"][];
            listingShippingCategories?: components["schemas"]["ListingShippingCategory"][];
        };
        ListingShippingCategory: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            listing?: components["schemas"]["Listing"];
            listingId?: string;
            shippingCategory?: components["schemas"]["ShippingCategory"];
            shippingCategoryId?: string;
        };
        Marketplace: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            name?: string;
            displayName?: string | null;
            theme?: components["schemas"]["Theme"] | null;
            brands?: components["schemas"]["Brand"][];
            categories?: components["schemas"]["Category"][];
            shippingCategories?: components["schemas"]["ShippingCategory"][];
            tags?: components["schemas"]["Tag"][];
        };
        Payout: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** @enum {string|null} */
            status?: "COMPLETED" | "PENDING" | "CANCELED" | null;
            /**
             * @default STRIPE
             * @enum {string|null}
             */
            paymentProcessingType: "STRIPE";
            paymentProcessingPayoutId?: string | null;
            /**
             * @default CARD
             * @enum {string|null}
             */
            paymentProcessingMethodType: "CARD" | "BANK_ACCOUNT";
            paymentProcessingtMethodId?: string | null;
            amount?: number | null;
            wallet?: components["schemas"]["Wallet"] | null;
            walletId?: string | null;
        };
        Product: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            name?: string | null;
            displayName?: string | null;
            description?: string | null;
            /** @enum {string|null} */
            type?: "CARD" | null;
            image?: string | null;
            price?: number | null;
            /** Format: date-time */
            releaseDate?: string | null;
            weight?: number | null;
            brandCategory?: components["schemas"]["BrandCategory"] | null;
            brandCategoryId?: string | null;
            list?: components["schemas"]["List"] | null;
            listId?: string | null;
            productTags?: components["schemas"]["ProductTag"][];
            card?: components["schemas"]["Card"] | null;
            reviews?: components["schemas"]["Review"][];
            bids?: components["schemas"]["Bid"][];
            listings?: components["schemas"]["Listing"][];
        };
        ProductTag: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            tagValue?: string;
            isPrimary?: boolean | null;
            index?: number | null;
            tag?: components["schemas"]["Tag"];
            tagId?: string;
            product?: components["schemas"]["Product"];
            productId?: string;
        };
        Profile: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            username?: string | null;
            /** @default false */
            isPrivate: boolean | null;
            fullName?: string | null;
            image?: string | null;
            qrCode?: string | null;
            account?: components["schemas"]["Account"];
            accountId?: string;
            lists?: components["schemas"]["List"][];
            reviews?: components["schemas"]["Review"][];
            bids?: components["schemas"]["Bid"][];
            listings?: components["schemas"]["Listing"][];
        };
        Review: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            rating?: number | null;
            description?: string | null;
            profile?: components["schemas"]["Profile"] | null;
            profileId?: string | null;
            product?: components["schemas"]["Product"] | null;
            productId?: string | null;
        };
        Shipment: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            fee?: number | null;
            /** @enum {string|null} */
            deliveryType?: "USPS" | "UPS" | "FEDEX" | "IN_PERSON" | null;
            /** @enum {string|null} */
            deliveryMethodType?: "FIRST_CLASS_MAIL" | "OVERNIGHT" | "PRIORITY" | "FLAT_RATE" | "ECONOMY" | "INTERNATIONAL" | null;
            trackingNumber?: string | null;
            transaction?: components["schemas"]["Transaction"];
            transactionId?: string;
        };
        ShippingCategory: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            name?: string | null;
            displayName?: string | null;
            description?: string | null;
            maxQuantity?: number | null;
            maxWeight?: number | null;
            price?: number | null;
            marketplace?: components["schemas"]["Marketplace"] | null;
            marketplaceName?: string | null;
            listingShippingCategories?: components["schemas"]["ListingShippingCategory"][];
            bidShippingCategories?: components["schemas"]["BidShippingCategory"][];
        };
        SupportedTagValues: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            name?: string | null;
            displayName?: string | null;
            tag?: components["schemas"]["Tag"] | null;
            tagId?: string | null;
        };
        Tag: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            name?: string;
            displayName?: string | null;
            marketplace?: components["schemas"]["Marketplace"] | null;
            marketplaceName?: string | null;
            productTags?: components["schemas"]["ProductTag"][];
            supportedTagValues?: components["schemas"]["SupportedTagValues"][];
        };
        Theme: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            logo?: string | null;
            primaryColor?: string | null;
            secondaryColor?: string | null;
            marketplace?: components["schemas"]["Marketplace"];
            marketplaceId?: string;
            brand?: components["schemas"]["Brand"];
            brandId?: string;
        };
        Transaction: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            subTotal?: number | null;
            tax?: number | null;
            total?: number | null;
            /** @enum {string|null} */
            status?: "COMPLETED" | "PENDING" | "CANCELED" | "REFUNDED" | null;
            bid?: components["schemas"]["Bid"] | null;
            bidId?: string | null;
            listing?: components["schemas"]["Listing"] | null;
            listingId?: string | null;
            shipment?: components["schemas"]["Shipment"] | null;
        };
        User: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /**
             * @default ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "INACTIVE" | "DELETED";
            authId?: string | null;
            account?: components["schemas"]["Account"] | null;
        };
        Wallet: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            balance?: number | null;
            payouts?: components["schemas"]["Payout"][];
            account?: components["schemas"]["Account"] | null;
            accountId?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;