/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Account: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /**
             * @default ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "INACTIVE" | "DELETED";
            /**
             * @default STANDARD
             * @enum {string}
             */
            type: "STANDARD" | "SELLER";
            /** @default false */
            isPremium: boolean | null;
            phone?: string | null;
            email?: string | null;
            firstName?: string | null;
            lastName?: string | null;
            address?: string | null;
            city?: string | null;
            state?: string | null;
            zipCode?: string | null;
            profile?: components["schemas"]["Profile"] | null;
            wallet?: components["schemas"]["Wallet"] | null;
            user?: components["schemas"]["User"];
            userId?: string;
        };
        Bid: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            amount?: number;
            /** @enum {string} */
            status?: "ACTIVE" | "INACTIVE" | "DELETED";
            profile?: components["schemas"]["Profile"] | null;
            profileId?: string | null;
            product?: components["schemas"]["Product"] | null;
            productId?: string | null;
            transaction?: components["schemas"]["Transaction"] | null;
        };
        Brand: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            name?: string;
            displayName?: string | null;
            marketplace?: components["schemas"]["Marketplace"] | null;
            marketplaceName?: string | null;
            theme?: components["schemas"]["Theme"] | null;
            brandCategories?: components["schemas"]["BrandCategory"][];
        };
        BrandCategory: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            brand?: components["schemas"]["Brand"];
            brandName?: string;
            category?: components["schemas"]["Category"];
            categoryName?: string;
            lists?: components["schemas"]["List"][];
            products?: components["schemas"]["Product"][];
            cards?: components["schemas"]["Card"][];
        };
        Card: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            number?: string | null;
            shippingCategory?: string | null;
            brandCategory?: components["schemas"]["BrandCategory"];
            brandCategoryId?: string;
            product?: components["schemas"]["Product"];
            productId?: string;
        };
        Category: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            name?: string;
            displayName?: string | null;
            marketplace?: components["schemas"]["Marketplace"] | null;
            marketplaceName?: string | null;
            brandCategories?: components["schemas"]["BrandCategory"][];
        };
        List: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            displayName?: string | null;
            name?: string | null;
            description?: string | null;
            /** @enum {string} */
            type?: "COLLECTION" | "SET" | "DECK" | "FAVORITE";
            brandCategory?: components["schemas"]["BrandCategory"];
            brandCategoryId?: string;
            products?: components["schemas"]["Product"][];
            profile?: components["schemas"]["Profile"] | null;
            profileId?: string | null;
        };
        Listing: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            amount?: number;
            /** @enum {string} */
            status?: "ACTIVE" | "INACTIVE" | "DELETED";
            profile?: components["schemas"]["Profile"] | null;
            profileId?: string | null;
            product?: components["schemas"]["Product"] | null;
            productId?: string | null;
            transaction?: components["schemas"]["Transaction"] | null;
        };
        Marketplace: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            name?: string;
            displayName?: string | null;
            theme?: components["schemas"]["Theme"] | null;
            brands?: components["schemas"]["Brand"][];
            categories?: components["schemas"]["Category"][];
            tags?: components["schemas"]["Tag"][];
        };
        Payout: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** @enum {string} */
            status?: "COMPLETED" | "PENDING" | "CANCELED";
            /**
             * @default STRIPE
             * @enum {string}
             */
            paymentProcessingType: "STRIPE";
            paymentProcessingPayoutId?: string;
            amount?: number;
            wallet?: components["schemas"]["Wallet"] | null;
            walletId?: string | null;
        };
        Product: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            displayName?: string | null;
            name?: string | null;
            description?: string | null;
            /** @enum {string} */
            type?: "CARD";
            image?: string | null;
            price?: string | null;
            /** Format: date-time */
            releaseDate?: string | null;
            brandCategory?: components["schemas"]["BrandCategory"];
            brandCategoryId?: string;
            list?: components["schemas"]["List"] | null;
            listId?: string | null;
            productTags?: components["schemas"]["ProductTag"][];
            card?: components["schemas"]["Card"] | null;
            reviews?: components["schemas"]["Review"][];
            bids?: components["schemas"]["Bid"][];
            listings?: components["schemas"]["Listing"][];
        };
        ProductTag: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            tagValue?: string;
            tag?: components["schemas"]["Tag"];
            tagId?: string;
            product?: components["schemas"]["Product"];
            productId?: string;
        };
        Profile: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            username?: string | null;
            /** @default false */
            isPrivate: boolean | null;
            fullName?: string | null;
            image?: string | null;
            qrCode?: string | null;
            account?: components["schemas"]["Account"];
            accountId?: string;
            lists?: components["schemas"]["List"][];
            reviews?: components["schemas"]["Review"][];
            bids?: components["schemas"]["Bid"][];
            listings?: components["schemas"]["Listing"][];
        };
        Review: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            rating?: number | null;
            description?: string | null;
            profile?: components["schemas"]["Profile"] | null;
            profileId?: string | null;
            product?: components["schemas"]["Product"] | null;
            productId?: string | null;
        };
        SupportedTagValues: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            name?: string;
            displayName?: string | null;
            tag?: components["schemas"]["Tag"];
            tagId?: string;
        };
        Tag: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            name?: string;
            displayName?: string | null;
            marketplace?: components["schemas"]["Marketplace"] | null;
            marketplaceName?: string | null;
            productTags?: components["schemas"]["ProductTag"][];
            supportedTagValues?: components["schemas"]["SupportedTagValues"][];
        };
        Theme: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            logo?: string | null;
            primaryColor?: string | null;
            secondaryColor?: string | null;
            marketplace?: components["schemas"]["Marketplace"];
            marketplaceId?: string;
            brand?: components["schemas"]["Brand"];
            brandId?: string;
        };
        Transaction: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            subTotal?: number;
            tax?: number | null;
            total?: number;
            /** @enum {string} */
            status?: "COMPLETED" | "PENDING" | "CANCELED" | "REFUNDED";
            /** @enum {string} */
            deliveryMethodType?: "FIRST_CLASS_MAIL" | "OVERNIGHT" | "PRIORITY" | "FLAT_RATE" | "ECONOMY" | "LOCAL_DELIVERY" | "IN_PERSON" | "INTERNATIONAL";
            trackingNumber?: string | null;
            bid?: components["schemas"]["Bid"];
            bidId?: string;
            listing?: components["schemas"]["Listing"];
            listingId?: string;
        };
        User: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /**
             * @default ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "INACTIVE" | "DELETED";
            cognitoId?: string;
            account?: components["schemas"]["Account"] | null;
        };
        Wallet: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /**
             * @default STRIPE
             * @enum {string}
             */
            paymentProcessingType: "STRIPE";
            paymentProcessingCustomerId?: string;
            /**
             * @default CARD
             * @enum {string}
             */
            paymentProcessingMethodType: "CARD" | "BANK_ACCOUNT";
            paymentProcessingtMethodId?: string;
            balance?: number | null;
            payouts?: components["schemas"]["Payout"][];
            account?: components["schemas"]["Account"];
            accountId?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
